#pragma once

#include "cli/command.hpp"

#include <string_view>

namespace mdtask {

/**
 * "completion" subcommand: prints the zsh completion script.
 *
 * The script is generated by sparcli's argument parser from the declared
 * command tree, so it never goes out of sync with the actual commands.
 * Users install it with:
 *
 *   mdtask completion > ~/.zsh/completions/_mdtask
 */
class CompletionCommand : public Command {
public:
    [[nodiscard]] std::string_view name() const override;
    [[nodiscard]] std::string_view summary() const override;
    void configure(sparcli::ArgsCmd command_node) override;
    [[nodiscard]] int run(const sparcli::Args& args) override;
};

}  // namespace mdtask
